controller_manager:
  ros__parameters:
    update_rate: 30  # 有小数点就会报错哦
    use_sim_time: false

    mecanum_controller:
      type: mecanum_drive_controller/MecanumDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

mecanum_controller:
  ros__parameters:
    reference_timeout: 0.9

    front_left_wheel_command_joint_name: "front_left_joint"
    front_right_wheel_command_joint_name: "front_right_joint"
    rear_right_wheel_command_joint_name: "rear_right_joint"
    rear_left_wheel_command_joint_name: "rear_left_joint"

    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.0375
      sum_of_robot_center_projection_on_X_Y_axis: 0.203

    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    enable_odom_tf: true
    # twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    # pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]


